version: '3.8'

services:

  # Base de données PostgreSQL
  maalem-db:
    image: postgres:15
    container_name: maalem_database
    restart: always
    environment:
      POSTGRES_DB: maalem_db
      POSTGRES_USER: maalem_user
      POSTGRES_PASSWORD: maalem_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serveur Dart
  maalem-backend:
    build:
      context: ./maalem_server
      dockerfile: Dockerfile
    container_name: maalem_api_server
    restart: always
    ports:
      - "8081:8081"
    environment:
      DB_HOST: maalem-db
      DB_PORT: 5432
      DB_NAME: maalem_db
      DB_USER: maalem_user
      DB_PASSWORD: maalem_pass
      JWT_SECRET: maalem_super_secret_key
    depends_on:
      - maalem-db

volumes:
  postgres_data: