name: maalem_server
description: Backend API pour la plateforme Maalem.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  postgres: ^3.3.2
  dart_jsonwebtoken: ^2.7.1
  crypto: ^3.0.3
  bcrypt: ^1.1.3