name: maalem_server
ports:
  - "8081:8081"
description: Backend API pour la plateforme Maalem.
version: 1.0.0
publish_to: 'none' # Empêche la publication accidentelle sur pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0' # C'est ICI que se trouvait l'erreur

dependencies:
  firedart: ^0.9.0 # Pour communiquer avec Firestore